### ISSUE TITLE
Preferences Structure for Dashboard

### ISSUE THREAD

**Issue by kiephil** [JaydenUlysses/Olaf-the-coolest-of-Bots#21]
To implement all controls for the preferences dashboard structure, I need a list of all parameters that you need to be able to set.

Structure:
I would suggest a service-based structure.
`Preferences.get('<service>', '<service><Setting>'),`

E.g. for the prefered category of a track selected by the Spotify Service, it would be structured like this:
`Preferences.get('spotify', 'spotifyCategory')`

This naming convention would make it easier in the dashboard frontend to build the forms that are used to save the preferences.

Please write a comment that lists all attributes and whether they hold a value from a list of possible values or they are user defined.
In case the values are pre-defined, they will be selectable by a `<select>` field. Please include a JSON array in your comment that lists them like this:
`{ id: '<value>', name: '<name>' }`

\<value> will be the value saved by the service, \<name> its display name shown in the select field.
E.g. a list of subreddits would be noted like this:
```
{ id: 'r/memes', name: 'r/memes' },
{ id: 'r/funny', name: 'r/funny' },
{ id: 'r/dankmemes', name: 'r/dankmemes' },
```

**Comment by DominikStiller** [comment]
**Preferences for the Image of the Day Use Case:**

My preferences are based on the use case rather than the service, I hope that's okay. They can all be in the `Image of the Day` preferences section.

* `imageofthedayProactive`: whether an image should be sent to the user at a certain time of the day proactively or just on demand
   * Values: true/false
   * Default: true
* `imageofthedayProactiveTime`: the time of the day at which to send the image of the day to the user (only enabled if `imageofthedayProactive == true`)
   * Values: any time in `hh:mm` 24-hour format
   * Default: `08:00`
* `imageofthedayRandom`: whether the image should be chosen completely randomly or based on certain tags
   * Values: true/false
   * Default: true
* `imageofthedayTags`: tags to choose an image by (only enabled if `unsplashRandom == false`), caption should mention that tags need to be comma-separated
   * Values: user-defined text
   * Default: empty string

**Comment by kiephil** [comment]
I'd say its fine unless a service you use is used by another usecase.
Thanks

**Comment by DominikStiller** [comment]
If your use case offers proactivity (i.e. automatic triggering of your use case at a certain time of the day), please follow the same format as the Image of the Day use case (naming, time format).

**Comment by CreaThor123** [comment]
I decided to yeet the preferences out of my use case. So from my side, no action is required from you, @kiephil :-)

**Comment by SonSon0815** [comment]
For the moment I plan to use two properties for the `daily financial status`:
- `dfstatusProactive`: boolean // indicates whether information should be sent automatically or only when triggered by the user
- `dfstatusProactiveTime`: string // the time the user wants to receive daily updates, 24 hour format represented in hh:mm, should only be able to be set if the `dfstatusProactive` value is set to true.

I'll drop other planned customization to save time and effort.

I'm not entirely sure whether another prefernce should be added for Google Authentication for the calendar but the authentication process requires a code presented in the browser and paste it to console which has to be done once, but seems unavoidable at the moment and a preference would not reduce the effort that much. So I tend to stay with those two preferences.

**Comment by JaydenUlysses** [comment]
news
newsKeywords:string[] // Default :[]
newsProactiveTime:string // Default 9:00
newsProactive:boolean // Default:True
